### ISSUE TITLE
work problem

### ISSUE THREAD

**Issue by arashzgh** [D4R4/BlizWoW#43] opened 2015-02-15 08:13 UTC
salam khaste nabashid work mining va herbalism moshkel dare residegi konid ye mine ya ye herb ke farm mikoni dg dar nemiad vase moddate kheyli toolanid masalan sholazar titanium farm mikoni dg resp nemishe herb ham hamintor

**Comment by D4R4** [comment] 2015-03-29 07:27
working as intended,closing

**Closed as completed by D4R4** 2015-03-29 07:27 UTC
